
import { GoogleGenAI, Modality } from "@google/genai";

const parseDataUrl = (dataUrl: string) => {
  const match = dataUrl.match(/^data:(.+);base64,(.+)$/);
  if (!match) {
    throw new Error('Invalid data URL format');
  }
  return {
    mimeType: match[1],
    data: match[2],
  };
};

export const generateTryOnImage = async (
  personImageDataUrl: string,
  clothingImageDataUrl: string
): Promise<string> => {
  if (!process.env.API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
  }
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const personImagePart = parseDataUrl(personImageDataUrl);
  const clothingImagePart = parseDataUrl(clothingImageDataUrl);

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: personImagePart.data,
            mimeType: personImagePart.mimeType,
          },
        },
        {
          inlineData: {
            data: clothingImagePart.data,
            mimeType: clothingImagePart.mimeType,
          },
        },
        {
          text: 'Analyze the two images. The first image contains a person and the second contains an item of clothing. Generate a new, photorealistic image showing the person from the first image wearing the clothing item from the second image. Ensure the fit and lighting are natural.',
        },
      ],
    },
    config: {
        responseModalities: [Modality.IMAGE],
    },
  });

  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      const { mimeType, data } = part.inlineData;
      return `data:${mimeType};base64,${data}`;
    }
  }

  throw new Error('No image was generated by the API.');
};
